feat: Query suggestions UI (#155)
Builds on #150 -- needs to be merged into that 

- adds a fix to the backend to make multi turn chat work 

this was the initial error when responding to a chat w/ a suggested
response
```
  httpx.HTTPStatusError: Error response 400 while fetching https://api.mistral.ai/v1/chat/
  completions: {"object":"error","message":"Unexpected role 'user' after role
  'tool'","type":"invalid_request_message_order","param":null,"code":"3230"}
  During task with name 'model' and id '927c4237-36d6-e8dd-1b40-321f82ed3d24'
 ```
 
- Modifies UI to support query suggestions 

<img width="541" height="920" alt="image" src="https://github.com/user-attachments/assets/4b046850-ab28-4320-9005-8a25b6467c48" />